version: '3.3'

services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 5000:5000
    tty: true
    volumes:
      - ./app/python/:/app
